#!/usr/bin/env python
from clusto.scripthelpers import init_script
from clusto.drivers import IPManager
from clusto.drivers import servers
import clusto

from optparse import OptionParser
import sys

def main():
    config, logger = init_script()

    parser = OptionParser(usage="usage: %prog [options] <pools...>")
    parser.add_option("-k", "--key", dest="key", default='ip')
    parser.add_option("-s", "--subkey", dest="subkey", default='ipstring')
    parser.add_option("-n", "--print-name", action="store_true", dest="print_name", default=False)
    options, args = parser.parse_args()

    if not args:
        parser.print_help()
        return -1

    for entity in clusto.get_from_pools(args):
        name = [entity.name] if options.print_name else []
        attrs = name + entity.attr_values(key=options.key, subkey=options.subkey)
        print ' '.join(attrs)

if __name__ == '__main__':
    sys.exit(main())
